# Generated by Django 3.2.5 on 2021-07-07 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_cat', models.CharField(max_length=100)),
                ('description_cat', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_clt', models.CharField(max_length=100)),
                ('prenom_clt', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('ville', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=20)),
                ('img_clt', models.ImageField(upload_to='clients/')),
            ],
        ),
        migrations.CreateModel(
            name='Compte_admi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Gamme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_gam', models.CharField(max_length=100)),
                ('description_gam', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prdt', models.CharField(max_length=100)),
                ('description_prdt', models.TextField()),
                ('marque', models.CharField(max_length=100)),
                ('prix', models.FloatField()),
                ('nombre_stock', models.IntegerField()),
                ('image_prdt', models.ImageField(upload_to='products/')),
                ('nom_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopApp.categorie')),
                ('nom_gam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopApp.gamme')),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse_livraison', models.CharField(max_length=100)),
                ('code_postal', models.CharField(max_length=20)),
                ('date_cmd', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopApp.client')),
            ],
        ),
    ]
