# Generated by Django 3.2.5 on 2021-07-07 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='nom_cat',
            new_name='categorie',
        ),
        migrations.RenameField(
            model_name='produit',
            old_name='nom_gam',
            new_name='gamme',
        ),
    ]
