# Generated by Django 3.2.5 on 2021-07-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0002_auto_20210707_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compte_admi',
            name='login',
        ),
        migrations.RemoveField(
            model_name='compte_admi',
            name='password',
        ),
        migrations.AddField(
            model_name='compte_admi',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compte_admi',
            name='photo',
            field=models.ImageField(blank=True, upload_to='costumers/'),
        ),
    ]
