# Generated by Django 3.2.5 on 2021-07-08 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0003_auto_20210708_1324'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Compte_admi',
            new_name='Compte_adm',
        ),
    ]
